### PR TITLE
toSeconds, toNanoseconds made exhaustive

### PR DESCRIPTION
**Pull request by monyschuk**
New issue with Xcode 9b3, it seems

### CODE REVIEW

**Comment by andreyz** [comment]
was about to suggest the same PR! thanks for beating me to it

**Comment by mattgallagher** [comment]
I tidied up the toNanosecond .never return value (it was returning Double) and wrapped the whole thing in #if swift (>=3.2) conditionals so it should work under Xcode 9 beta 3 and later or Xcode 8.3 or earlier. Everyone in the middle... that's the fun of betas.

**Comment by andreyz** [comment]
Please cut a new beta 17(?) and reference that from CwlSignal, stops my project building otherwise. Thanks!

**Comment by mattgallagher** [comment]
Done.

**Pull request merged**
